### PR TITLE
Updated dependencies to fix security vulnerabilities

### PR DESCRIPTION
**Pull request by mayankkulkarni**
I have updated the dependencies from the security report that were vulnerabilities. Please take a look at the same.

### CODE REVIEW

**Comment by GreatYYX** [comment]
@mayankkulkarni there are lots of bin files, are they required or can be auto generated on user side (if so, they should be in gitignore)?

**Comment by mayankkulkarni** [comment]
@GreatYYX Yes they can be put in gitignore. They are generated when the repository is built using maven.

**Comment by GreatYYX** [comment]
@mayankkulkarni please remove them and add them to gitignore, then update the PR, thanks.

**Comment by rutujarane** [comment]
Security vulnerabilities fixed.

**Pull request closed without merging**
